namespace FindHoneyPos.Tests.Services;

using FindHoneyPos.Core.Constants;
using FindHoneyPos.Core.Entities;
using FindHoneyPos.Core.Enums;
using FindHoneyPos.Core.Interfaces;
using FindHoneyPos.Infrastructure.Data;
using FindHoneyPos.Infrastructure.Services;
using FindHoneyPos.Tests.Helpers;
using FluentAssertions;
using Moq;

public class OrderServiceTests : IDisposable
{
    private readonly AppDbContext _context;
    private readonly OrderService _service;
    private readonly Mock<IMaterialService> _materialServiceMock;

    public OrderServiceTests()
    {
        _context = TestDbContextFactory.Create();
        _materialServiceMock = new Mock<IMaterialService>();
        _service = new OrderService(_context, _materialServiceMock.Object);
    }

    public void Dispose() => _context.Dispose();

    #region CreateAsync

    [Fact]
    public async Task CreateAsync_ShouldAutoGenerateDailySequence()
    {
        var order = TestDataBuilder.CreateOrder();
        order.Items.Add(TestDataBuilder.CreateOrderItem());

        var result = await _service.CreateAsync(order);

        result.DailySequence.Should().Be(BusinessRules.InitialOrderSequence + 1);
    }

    [Fact]
    public async Task CreateAsync_ShouldGenerateOrderNumberFormat()
    {
        var order = TestDataBuilder.CreateOrder();
        order.Items.Add(TestDataBuilder.CreateOrderItem());

        var result = await _service.CreateAsync(order);

        result.OrderNumber.Should().Be("#0126");
    }

    [Fact]
    public async Task CreateAsync_ShouldCalculateSubtotalWithAddons()
    {
        var order = TestDataBuilder.CreateOrder();
        var item = TestDataBuilder.CreateOrderItem(price: 50m, quantity: 2);
        item.Addons.Add(TestDataBuilder.CreateAddon(price: 10m));
        item.Addons.Add(TestDataBuilder.CreateAddon(productName: "椰果", price: 15m));
        order.Items.Add(item);

        var result = await _service.CreateAsync(order);

        // (50 + 10 + 15) * 2 = 150
        result.Items.First().Subtotal.Should().Be(150m);
    }

    [Fact]
    public async Task CreateAsync_ShouldCalculateSubtotalWithoutAddons()
    {
        var order = TestDataBuilder.CreateOrder();
        var item = TestDataBuilder.CreateOrderItem(price: 80m, quantity: 3);
        order.Items.Add(item);

        var result = await _service.CreateAsync(order);

        result.Items.First().Subtotal.Should().Be(240m);
    }

    [Fact]
    public async Task CreateAsync_SecondOrder_ShouldIncrementSequence()
    {
        var order1 = TestDataBuilder.CreateOrder();
        order1.Items.Add(TestDataBuilder.CreateOrderItem());
        await _service.CreateAsync(order1);

        var order2 = TestDataBuilder.CreateOrder();
        order2.Items.Add(TestDataBuilder.CreateOrderItem());
        var result = await _service.CreateAsync(order2);

        result.DailySequence.Should().Be(BusinessRules.InitialOrderSequence + 2);
        result.OrderNumber.Should().Be("#0127");
    }

    [Fact]
    public async Task CreateAsync_ShouldPreserveExistingDailySequence()
    {
        var order = TestDataBuilder.CreateOrder(dailySequence: 200);
        order.Items.Add(TestDataBuilder.CreateOrderItem());

        var result = await _service.CreateAsync(order);

        result.DailySequence.Should().Be(200);
    }

    [Fact]
    public async Task CreateAsync_ShouldPreserveExistingOrderNumber()
    {
        var order = TestDataBuilder.CreateOrder();
        order.OrderNumber = "#9999";
        order.DailySequence = 9999;
        order.Items.Add(TestDataBuilder.CreateOrderItem());

        var result = await _service.CreateAsync(order);

        result.OrderNumber.Should().Be("#9999");
    }

    [Fact]
    public async Task CreateAsync_MultipleItems_ShouldCalculateEachSubtotal()
    {
        var order = TestDataBuilder.CreateOrder();
        var item1 = TestDataBuilder.CreateOrderItem(price: 100m, quantity: 1);
        item1.Addons.Add(TestDataBuilder.CreateAddon(price: 10m));
        var item2 = TestDataBuilder.CreateOrderItem(productName: "紅茶", price: 40m, quantity: 2);
        order.Items.Add(item1);
        order.Items.Add(item2);

        var result = await _service.CreateAsync(order);

        result.Items.First(i => i.ProductName == "測試商品").Subtotal.Should().Be(110m);
        result.Items.First(i => i.ProductName == "紅茶").Subtotal.Should().Be(80m);
    }

    #endregion

    #region BatchCreateAsync

    [Fact]
    public async Task BatchCreateAsync_ShouldSkipDuplicateDeviceIdAndTimestamp()
    {
        var ts = DateTime.UtcNow;
        var order1 = TestDataBuilder.CreateOrder(deviceId: "device1", timestamp: ts);
        order1.Items.Add(TestDataBuilder.CreateOrderItem());
        await _service.CreateAsync(order1);

        var duplicate = TestDataBuilder.CreateOrder(deviceId: "device1", timestamp: ts);
        duplicate.Items.Add(TestDataBuilder.CreateOrderItem());

        var results = await _service.BatchCreateAsync(new[] { duplicate });

        results.Should().BeEmpty();
    }

    [Fact]
    public async Task BatchCreateAsync_DifferentDeviceId_ShouldAllowSameTimestamp()
    {
        var ts = DateTime.UtcNow;
        var order1 = TestDataBuilder.CreateOrder(deviceId: "device1", timestamp: ts);
        order1.Items.Add(TestDataBuilder.CreateOrderItem());
        await _service.CreateAsync(order1);

        var order2 = TestDataBuilder.CreateOrder(deviceId: "device2", timestamp: ts);
        order2.Items.Add(TestDataBuilder.CreateOrderItem());

        var results = await _service.BatchCreateAsync(new[] { order2 });

        results.Should().HaveCount(1);
    }

    [Fact]
    public async Task BatchCreateAsync_NullDeviceId_ShouldNotSkip()
    {
        var ts = DateTime.UtcNow;
        var order1 = TestDataBuilder.CreateOrder(deviceId: null, timestamp: ts);
        order1.Items.Add(TestDataBuilder.CreateOrderItem());

        var order2 = TestDataBuilder.CreateOrder(deviceId: null, timestamp: ts);
        order2.Items.Add(TestDataBuilder.CreateOrderItem());

        var results = await _service.BatchCreateAsync(new[] { order1, order2 });

        results.Should().HaveCount(2);
    }

    [Fact]
    public async Task BatchCreateAsync_MixedOrders_ShouldCreateNonDuplicates()
    {
        var ts = DateTime.UtcNow;
        var existing = TestDataBuilder.CreateOrder(deviceId: "d1", timestamp: ts);
        existing.Items.Add(TestDataBuilder.CreateOrderItem());
        await _service.CreateAsync(existing);

        var dup = TestDataBuilder.CreateOrder(deviceId: "d1", timestamp: ts);
        dup.Items.Add(TestDataBuilder.CreateOrderItem());
        var fresh = TestDataBuilder.CreateOrder(deviceId: "d2", timestamp: ts);
        fresh.Items.Add(TestDataBuilder.CreateOrderItem());

        var results = await _service.BatchCreateAsync(new[] { dup, fresh });

        results.Should().HaveCount(1);
    }

    #endregion

    #region GetAllAsync

    [Fact]
    public async Task GetAllAsync_ShouldReturnPaginatedResults()
    {
        for (int i = 0; i < 5; i++)
        {
            var o = TestDataBuilder.CreateOrder();
            o.Items.Add(TestDataBuilder.CreateOrderItem());
            await _service.CreateAsync(o);
        }

        var (orders, total) = await _service.GetAllAsync(page: 1, pageSize: 2);

        orders.Count().Should().Be(2);
        total.Should().Be(5);
    }

    [Fact]
    public async Task GetAllAsync_ShouldFilterByStatus()
    {
        var completed = TestDataBuilder.CreateOrder(status: OrderStatus.Completed);
        completed.Items.Add(TestDataBuilder.CreateOrderItem());
        await _service.CreateAsync(completed);

        var cancelled = TestDataBuilder.CreateOrder(status: OrderStatus.Cancelled);
        cancelled.Items.Add(TestDataBuilder.CreateOrderItem());
        await _service.CreateAsync(cancelled);

        var (orders, total) = await _service.GetAllAsync(status: OrderStatus.Completed);

        total.Should().Be(1);
        orders.First().Status.Should().Be(OrderStatus.Completed);
    }

    [Fact]
    public async Task GetAllAsync_ShouldFilterByDateRange()
    {
        var today = DateTime.UtcNow.Date;
        var todayOrder = TestDataBuilder.CreateOrder(timestamp: today.AddHours(10));
        todayOrder.Items.Add(TestDataBuilder.CreateOrderItem());
        await _service.CreateAsync(todayOrder);

        var oldOrder = TestDataBuilder.CreateOrder(timestamp: today.AddDays(-3));
        oldOrder.Items.Add(TestDataBuilder.CreateOrderItem());
        await _service.CreateAsync(oldOrder);

        var (orders, total) = await _service.GetAllAsync(startDate: today, endDate: today.AddDays(1));

        total.Should().Be(1);
    }

    [Fact]
    public async Task GetAllAsync_ShouldIncludeItemsAndAddons()
    {
        var order = TestDataBuilder.CreateOrder();
        var item = TestDataBuilder.CreateOrderItem();
        item.Addons.Add(TestDataBuilder.CreateAddon());
        order.Items.Add(item);
        await _service.CreateAsync(order);

        var (orders, _) = await _service.GetAllAsync();

        var fetched = orders.First();
        fetched.Items.Should().HaveCount(1);
        fetched.Items.First().Addons.Should().HaveCount(1);
    }

    #endregion

    #region GetByIdAsync

    [Fact]
    public async Task GetByIdAsync_ShouldReturnCompleteOrderGraph()
    {
        var order = TestDataBuilder.CreateOrder();
        var item = TestDataBuilder.CreateOrderItem();
        item.Addons.Add(TestDataBuilder.CreateAddon());
        order.Items.Add(item);
        var created = await _service.CreateAsync(order);

        var result = await _service.GetByIdAsync(created.Id);

        result.Should().NotBeNull();
        result!.Items.Should().HaveCount(1);
        result.Items.First().Addons.Should().HaveCount(1);
    }

    [Fact]
    public async Task GetByIdAsync_NotFound_ShouldReturnNull()
    {
        var result = await _service.GetByIdAsync(999);

        result.Should().BeNull();
    }

    #endregion

    #region GetStatsAsync

    [Fact]
    public async Task GetStatsAsync_ShouldOnlyCountTodayOrders()
    {
        var today = DateTime.UtcNow.Date;
        var todayOrder = TestDataBuilder.CreateOrder(total: 200m, timestamp: today.AddHours(10));
        todayOrder.Items.Add(TestDataBuilder.CreateOrderItem());
        await _service.CreateAsync(todayOrder);

        var oldOrder = TestDataBuilder.CreateOrder(total: 100m, timestamp: today.AddDays(-1));
        oldOrder.Items.Add(TestDataBuilder.CreateOrderItem());
        await _service.CreateAsync(oldOrder);

        var stats = await _service.GetStatsAsync();

        var dict = ToDictionary(stats);
        ((int)dict["totalOrders"]).Should().Be(1);
    }

    [Fact]
    public async Task GetStatsAsync_ShouldSeparateCompletedAndCancelled()
    {
        var today = DateTime.UtcNow.Date;
        var completed = TestDataBuilder.CreateOrder(status: OrderStatus.Completed, total: 300m, timestamp: today.AddHours(10));
        completed.Items.Add(TestDataBuilder.CreateOrderItem());
        await _service.CreateAsync(completed);

        var cancelled = TestDataBuilder.CreateOrder(status: OrderStatus.Cancelled, total: 100m, timestamp: today.AddHours(11));
        cancelled.Items.Add(TestDataBuilder.CreateOrderItem());
        await _service.CreateAsync(cancelled);

        var stats = await _service.GetStatsAsync();
        var dict = ToDictionary(stats);

        ((int)dict["completedOrders"]).Should().Be(1);
        ((int)dict["cancelledOrders"]).Should().Be(1);
        ((decimal)dict["totalRevenue"]).Should().Be(300m);
    }

    [Fact]
    public async Task GetStatsAsync_EmptyOrders_ShouldReturnZeros()
    {
        var stats = await _service.GetStatsAsync();
        var dict = ToDictionary(stats);

        ((int)dict["totalOrders"]).Should().Be(0);
        ((decimal)dict["totalRevenue"]).Should().Be(0m);
    }

    #endregion

    #region GetNextDailySequenceAsync

    [Fact]
    public async Task GetNextDailySequenceAsync_NoOrders_ShouldReturnInitialPlusOne()
    {
        var result = await _service.GetNextDailySequenceAsync();

        result.Should().Be(BusinessRules.InitialOrderSequence + 1);
    }

    [Fact]
    public async Task GetNextDailySequenceAsync_ShouldIgnoreYesterdayOrders()
    {
        var yesterday = DateTime.UtcNow.Date.AddDays(-1).AddHours(10);
        var order = TestDataBuilder.CreateOrder(timestamp: yesterday, dailySequence: 200);
        order.OrderNumber = "#0200";
        order.Items.Add(TestDataBuilder.CreateOrderItem());
        _context.Orders.Add(order);
        await _context.SaveChangesAsync();

        var result = await _service.GetNextDailySequenceAsync();

        result.Should().Be(BusinessRules.InitialOrderSequence + 1);
    }

    #endregion

    private static Dictionary<string, object> ToDictionary(object obj)
    {
        return obj.GetType().GetProperties()
            .ToDictionary(p => p.Name, p => p.GetValue(obj)!);
    }
}
